version: "3.9"
services:
  baseball-chip-schedule-service:
    build: .
    ports:
      - "6060:6060"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image:
      redis
    ports:
      - "6379:6379"